name: Run Python Scripts

on:
  push:
    branches:
      - main
      - Test-Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 
        
    - name: Install Docker module
      run: pip install docker

    - name: Run first Python script
      run: python SBOM_Generator.py

    - name: Run second Python script
      run: python Upload_SBOM.py
